# How it began...

I remember the first time some 15 years ago when a colleague at work introduced me to the burrito,  and delicious as it was, I barely managed to finish it. Same with the foot-long. It was just too much food, more than what I needed to eat for lunch. Over the years I got more used to it and what used to be a huge portion size once, was just very normal now. What was almost a culture shock many years ago, was just routine now. It should not have been.

About 3 years ago i.e. in the spring of 2017, I decided to go to the doctor and ask why do I wake up with a severe case of dry mouth every morning? I knew I was grossly over-weight and the dry mouth had started happening a few years ago and the two could be related. I kept ignoring it for years, but it had become bad enough that I sometimes used to wake up very early in the morning because of it and had to rinse my mouth to go back to sleep. The doctor's visit was an eye opener, he said it is most certainly because you are grossly over-weight (I weighed 273 pounds) but asked a few more questions which led him to believe I had all the symptoms of sleep apnea.

TL;DR I did a home sleep apnea test and the results were very alarming. The doctor said it was so bad that I could be at the stage of starting to lose short term memory i.e. because the sleep is so disrupted because of lack of oxygen that the brain is not able to make new neural connections that it usually does when we are sleeping. This was happening when I had just joined a masters program in data science at Georgetown University and was now part time at school, 16 years after having completed my engineering degree. With my day job and school homework, my sleep time was anyway much reduced and not getting quality sleep was just bad in so many ways.

## My tryst with a protein-based diet

Something had to be done. I got on a medically supervised weight loss program that used a ketogenic/protein meal replacement diet and I started sleeping with a CPAP (Continuous positive airway pressure therapy). I count those two decisions among the top 5 best decisions of all time I ever took in my life. I followed the diet very strictly, of course my dear wife Nidhi was with me in this and she did the diet as well. I started losing weight immediately, sleeping with the CPAP machine was what I would call a life changing experience. I no longer felt like dozing off while driving to college, even if I slept 5 hours (which was 4 days a week) I still woke up refreshed and did not experience the mid afternoon crash in energy. In a couple of months, the weight loss, for both me and my wife, was very noticeable and friends and family started asking what were we doing that was causing this transformation. Everyone is interested in the new diet that their friends are into (especially if they are getting thinner:)). Expected case of FOMO, I would say. In about 8 to 9 months, I had lost close to 70 pounds and my wife had lost close to 40 pounds, that is drastic by any measure. It was effective, expensive and un-sustainable!

For about 10 months or so till I followed the diet, we were pretty strict about no or as little carbohydrates as possible and ate a lot of those protein supplements (bars, shakes, snacks etc.). Then came the holiday season, new year parties and there it was, the dreaded phase where I thought OK, we can go off course for a little bit and then get back on when this season is over. No prizes for guessing, it never happened. I still remember my weight had gone down to 202 pounds and I could see it rising back up, day after day. I thought OK, this is still less than 210, I can pull it back, no problem. Well, not really, soon it was past 210. I told myself, OK but it is not 220 yet, I can pull this back. Once it crossed the 230 pounds mark, I gave up trying.

I was able to graduate two years later (in 2019), my weight at 240 pounds and the CPAP machine by my bed every night. I did not even go for a weekend getaway without it. The dry mouth was getting back, not as bad though, but it was back, there was no missing it. The sleep was not as good. By end of 2019, I was 250 pounds, the CPAP machine was broken, my wardrobe almost completely redone because none of the clothes fit me anymore and I had given away all the clothes from 2017.

## A new beginning

Cliched as it is, I made a new year resolution in Jan 2020, "I need to fix myself, this cannot continue". Nidhi had also gained weight, not as much as me, but she gained 20 pounds out of the 40 she had lost. She had mentioned to me in December 2019 that there was this personal trainer who had dropped in to the Doctor's office (I conveniently skipped to mention that Nidhi became a health coach and started volunteering in the Doctor's office) and left her card if someone coming in for fitness training wanted to come for a trial class at her gym.

It is said, good things happen when the time is right (no one says that, I just made that one up :)). Nidhi left the trainer a message, and we did not hear back from her until a few days later when she said sure we could stop by her gym for a free class. There we were, on January 17th, 2020, in her gym, for what I did not know at the time would be the start of a new chapter in our life.

The gym itself was unassuming, in an extended but disjoint part of her house. I did not think much of it, but little did I know what we were getting into. It needs to be said that prior to this I had never seen the inside of a gym in real life and my only window into how fitness equipment looks like and what trainers do was through films and TV, in other words, what I knew was far from reality. I remember asking before the training "So what do you think, how many calories would we burn during the workout today?" and the answer I got was "Oh I don't know, we don't count calories here :)". "Ok, then" I remember saying to myself. The trainer seemed to be a pleasant person with an infectious smile, the training was good, tiring but not hard and I was like "OK, this isn't too bad". Later that evening, I felt a sharp pain in my neck, but I thought it is nothing. As the evening progressed, the pain increased. I barely got any sleep that night, even after putting some pain reliving ointments, the pain did not subside. It was the most physical pain I had endured in a long time. I even thought to myself, maybe I would need to put in a collar around my neck (I didn't need to). It took a couple of days for the pain to go away completely. Thankfully, that was the only time I felt such pain in all the months now that we have been exercising. Was a good lesson for me right at the start, never be under any false sense of bravado while working out in the gym (or even otherwise :)).

We decided to enroll for two classes a week. Since we were just starting out and I needed individual attention, we decided why don't we do a couple's package where we would have classes for a month for just the two of us together. She also asked us to fill out a detailed log, as detailed as we could get, of everything we ate or drank for 3 consecutive days. It was not convenient, but we scribbled something and gave it to her in the next class. The trainer had a small book that she and her husband had written about her journey with what they called (don't know it might be a standard term) "clean eating". There is a 30-day clean eating challenge in which you eat no processed food, no dairy, no pulses, no legumes, no hard drinks and no soft drinks either, only vegetables, fruits and meats are allowed. We decided to do the challenge and made a list of everything we thought we could eat during the challenge and got her to say Yay or Nay on each of those items. The list is in appendix A of this book. It had things commonly found in Indian kitchens like "spices", "herbs", different fruits etc. Now that I think about it, I am not sure what made me do the challenge, I just decided to do it just like I decided to workout in the gym twice a week, something that I had never done in almost my 41 years of life. When thoughts become deep, intentions become weak. So, there we were, working out twice a week in the gym and decided to go for clean eating in a few weeks' time.

What endeared me to the workout sessions was that after a few weeks I noticed both in myself and my wife there was an unmistakable feeling of joy/elation/happiness as we completed a hard training session in the gym. We did lose some pounds but nothing very noticeable. What attracted me to the clean eating was that I could identify with it, it did not claim any magic results, did not ask to give up on the basics i.e. vegetables/fruits/meat in fact it embraced these and only said do not eat processed food. This was the same guidance I had grown up with during my childhood, this was what my grandmother used to say as well, surely this could not go wrong. Surely nothing bad could happen by not eating cakes and cookies, not drinking soft drinks or hard drinks and just basically saying goodbye to processed sugar. Made total sense.

So here we were, ready to start and reminding ourselves **that the only way to reach the finish line is to start...**. My target was simple i.e. "not to be obese" as per the [NIH guidelines](https://www.nhlbi.nih.gov/health/educational/healthdisp/pdf/tipsheets/Are-You-at-a-Healthy-Weight.pdf), provided. I do not remember the time I was at 158 pounds, I just wanted to be 190 or less so that I would not be adding to the "obese" population of the planet. Nidhi on the other hand was reasonably fit and her goal was close to the NIH guidelines. I had the motivation, the means and had made up my mind.


```{r echo=FALSE, fig.height=10, fig.width=14}
df_starting_and_target_weights %>%
  group_by(name) %>%
  mutate(position = rank(-value)) %>%
  ggplot(aes(x=name, y=value, fill=metric, col=metric, group=position)) +
  geom_bar(stat="identity", position="dodge") +
  geom_text(aes(x=name, y=value+10, label = paste0("(", value, ")")),
            position = position_dodge(width = 1),
            #nudge_y = 0.015*df_starting_and_target_weights$value,
            show.legend = FALSE, size=8) + 
  labs(title="How things stood the day we started",
       subtitle=glue("All weights in pounds. Starting date: {min(df_P2$Date, na.rm=TRUE)}."),
       caption="Note: Ideal weight as per NIH guidelines.") +
  theme_fivethirtyeight() + 
  scale_fill_tableau() + 
  scale_color_tableau() +
  theme(legend.title = element_blank(), text=element_text(size=CHART_ELEMENT_TEXT_SIZE))
```

## Looking back

With the benefit of hindsight having been on this journey for close to two years now, here are some closing thoughts for this chapter on new beginnings.

Whenever we start something new, even if it is something as personal and discrete as a change in eating habits and fitness regimen, as people around us learn about it there are two kind of reactions one can expect, broadly speaking. One is a reaction of genuine encouragement which comes from a place of care, concern and wellbeing. This is usually from immediate family and close friends. The second is that of nonchalance disguised as an overt display of encouragement. Almost as if to say that you are trying a new fad, sure, try it for a few weeks, soon you would give up and be back to the same place as all of us or as a data scientist would call it, "you would regress to the mean". We should use both these reactions in a positive manner, even people who are indifferent today would be appreciative when they see the results in the months and years that follow (I purposefully did not say "weeks" but months and years). The fact that we started our journey in 2020 did help in this regard, we hardly met anyone in person for a greater part of the year, so most of the external inputs at the start of our journey, were just not present so we did not have to deal with them. While some of us might be completely self-driven with no need for the fuel of external encouragement to power our journey, but most aren't. As I realized later, it feels good to be appreciated :). Nothing like a little bit of positive reinforcement from family, friends, acquaintances or a random person walking up to you in a social gathering to say "you look so much fitter than last I saw you, what have you been doing?" to fire those dopamine neurons which will make you get up and move (very literally).

I would end this chapter by saying most people overestimate what they can achieve in the short term and underestimate what they can achieve in the long-term. Usually what we think of as short term targets either don't get achieved because they were never achievable in the short term to begin with (like fitness, wealth creation) or even if they are achieved we end up losing them (again, fitness and wealth creation seem to be the perfect examples here). In the world we live in today, setting your eyes on a long term goal and then working towards it without getting discouraged by failures that would inevitably happen along the way is a little bit of a challenge. If someone told me in January of 2020 that it would take 15 months of a lifestyle change comprising of nutrition and regular workouts to reach to my weight and BMI goals, I would have had moments of self-doubt. The trick is to acknowledge the self-doubts but focus on the resolve or maybe just don't think anything at all and just take the plunge (which is what I did). You would be surprised to see encouragement pouring in from unexpected quarters, the universe does conspire to make you successful!

## Chapter 3: At a glance

***

1. A change in lifestyle is usually triggered by a life changing event which often is a health scare. Don't wait for it to happen, make the switch to a sustainable healthy lifestyle now.

2. If the change you make is not something you can sustain for a long time, it will not last and ultimately all the gains you made would be lost. We found that a high protein low carb diet and no workouts, did not work for us as we found it to be unsustainable.

3. Clean eating and with regular workouts could be an ideal start for someone trying to make the switch. 





