# Exercise: Putting in the hard yards

You would have probably heard that managing weight is 70% about nutrition and 30% about exercise. I think this correct. Having said that, we should not downplay the 30% i.e the exercise. As I have mentioned earlier in the book, a few years back I tried a purely diet based plan and achieved good results. The problem with it, like with all diet based plans, was that it was not sustainable. There is another aspect to this as well, when I tried losing weight purely via the diet route (could also call it calorie counting) my overall appearance became thinner or I would even say weaker. While I do not recall feeling lack of energy but the appearance was as if I had just lost a lot of weight and it did not look healthy. Several people asked me out of genuine concern if I was sick and when I told them that I was doing this diet their reactions were on the lines of "ok, but don't do more of it". This time however, things are different, both me and my wife look leaner and fitter. Our body structure has become "denser" if that is the right word to use here and it is because of that we look thinner, fit into much smaller clothes. Appearance wise we do not have the starved look that I suppose comes from severe calorie restricted diets. Without a doubt, this is the result of the rather intensive exercise routine that we now have.

## There is always a 1st time

When I went to the gym for the first time this year, it was not just the first time for me for this year 2020 but it was for the first time in my entire 41 years. I had no illusions of how supremely unfit I was and how difficult this was going to be. Sometimes, I used to see people exiting after their class and I used to tell myself "OK, that person looked great, but that is probably because he has been working out since forever". Ofcourse, this may or may not have been true, but my goal was to keep telling myself that if I was disciplined enough to show up rain or shine and do the exercises as told then I would get better, that is just how it works. 

I look at some old videos now of me doing exercises like planks or air-squats when I started and I compare them with the more recent ones of me doing the same exercise. My movements used to be very clumsy, and it is to the credit of the trainer that she did not give up on me. Nidhi on the other hand, is almost a fitness model, being a dancer, her movements had a natural rhythm, she had flexibility, speed and having done some exercises while growing up, she was much more comfortable with the whole setup. 

We started with working out twice a week, and then went to thrice, and then four times and now I work out five times a week. Nidhi tried the four times a week routine but is now nicely settled at three times a week. In 8 months I have come from having to push myself to workout twice a week to now seems like my body cannot have enough of it.

One day a couple of months into training, I stumbled upon a YouTube video of the training routine of an actress who played the role of a superhero in one of her movies. Her trainer said when she came to the gym and looked at people doing pullups and deadlifts, her reaction was that oh yeah this is cool but I cant do that, and a few months later she was deadlifting 235 pounds. When I saw the video, I had a similar reaction. I thought sure, a Hollywood actress with a celebrity trainer can ofcourse do this, I can't. I was wrong. I now deadlift 255 pounds, and while I haven't done pullups yet, I can at least visualize myself doing them, not easy, but definitely possible.

