# Other Topics

This chapter covers miscellaneous topics which are quite important but I did not have enough material to give them a chapter of their own so I parked them all here.

## Time Restricted Eating

Or as everyone like to call it "intermittent fasting". I can end this section by simply saying please read this excellent book called "The Circadian Clock", it will provide you all the evidence based reasoning you need to try out TRE. I tried time restricted eating while doing exercise 4 to 5 days a week I personally found the results to be great.

As a matter of habit now, I eat within a 12 hour window and helps me feel light and energetic. I try finishing up dinner by 7 - 7:30pm and usually sleep by 11.30pm. Some days if I am working late into the night then I do feel a little but hungry, and if feel really hungry then I have half a cup of almond milk and that usually calms the rumblings in the stomach. 

I try doing a 14 hour fasting and 10 hour eating window every now and then, works fine. I have also tried a 22 hour fasting and 2 hour eating window once a week for a few weeks. Other than the fact that the brain says why are you not eating, I did not feel any discomfort. I even exercised on a 22-2 day, no problem at all.

What I have also experienced is that a day of 22-2 TRE does indeed help offset any indiscretions of the day before. I have tried this a couple of times, if I had gone overboard with a heavy dinner, ice-cream or other goodies during the day then doing a 22-2 the next day helps. I have no scientific data on this but just my own anecdotal evidence.

## What about supplements?

We did take some supplements, not for muscle building but for general health.

## For the love of charts

Here are some more charts that I could not fit anywhere else.


