# Breathwork


**NOTE**: In this chapter I refer to specific people and books, I would like to put it on record that this book is not endorsed by them, whatever I write here is my understanding of what I read from their books or saw from their videos.  

* * *

I am a software developer by training. One of the things that I learnt early on was that if you wanted to optimize a computer program so that it ran faster then you wanted to optimize the one module that in itself might appear trivial and hidden from the user visible functionality but was performed repeatedly and therefore any improvement in it had a multiplicative effect on the performance of the overall program. Breathing is that hidden module in the human system. We breath about 20,000 times a day on an average, it is an involuntary action for the most part and even a small improvement in breathing can have a huge impact on our health, both mental and physical.

When I started training, our trainer told us about breathing patterns appropriate for a particular exercise but I did not focus on that too much because I was so new to workout and exercise and my forms were so clumsy that adding a breathing pattern to an exercise was just one thing too many. As my forms improved, some basic movements and bracing became a part of habit and I did not actively need to be aware of them, they just happened, maybe that freed up some of my brain to focus on the missing link i.e. breathing. In any case, that is hindsight. It all started with me reading James Nestor's wonderful book called "Breath: the new science of a lost art". I think I stumbled upon some YouTube video about it, I don't remember for sure but as I read a little bit about the book I was convinced I need to read it. I am so happy that I did. The book has many references to ancient Indian breathing practices and I asked myself "why am I not trying some if not all of this?". After finishing that book, I read Dr Belisa Vranich's book "Breathing for warriors" and devoured every YouTube video and podcast I could find about breathwork.

## Two fundamentals

The two most fundamental things that you can (and should) so are nasal breathing and horizontal breath or belly breathing. First up, the mouth is not meant for breathing the nose is, unless you are completely out of breath say while doing a hard exercise routine, you should not normally need to breath through your mouth. Breathing through the nose offers a natural filtering mechanism to keep the harmful things out of your body, prevents dental problems and in general helps keep you calm and relaxed. I remember growing up, I used to have frequent colds and used to breath through my mouth a lot and my mother had a very tough time constantly reminding me (often in public) to keep my mouth closed. As I grew up and my immunity got better, the frequent colds went away and while I did not breath through my mouth as much but it was not something that I paid attention to, not sure most people do.

After reading James Nestor's book I started being conscious about nose breathing and any time I found myself breathing through the mouth I immediately switched to nose breathing. Then one day I decided to see if I could train with my mouth closed and only breathing through the nose. I barely made it past the 5 minute warmup before I had to open my mouth for breathing. I persisted, and it got better, in a couple of weeks I could finish a 10-15 minute strength training portion of the portion of the workout which usually involved heavy deadlifts, back squats or other compound exercises. Whenever I did heavy cardio, such as sprints, a few calories on the assault bike, burpees and such I had to open my mouth. I knew I was getting better though. A couple of months into the nose breathing and I could finish the cardio portion as well. Today (about 6 months in), I am able to complete the entire 50-60 minute workout without having to breath through my mouth, and more importantly, I do not even feel the need to (of course talking to the trainer or having a sip of water means I do breath through my mouth in between sets). I no longer feel out of breath while working out, my heart rate remains under 140 even during intense cardio and my endurance levels improved tremendously.

The other fundamental is horizontal breathing or belly breath or diaphragmatic breathing. Put simply, a belly breath means expanding your belly as you inhale so that your lungs push your diaphragm down and contracting your belly while exhaling so that your diaphragm expands and moves upwards. This is best understood by seeing some visualizations and videos, there are many, but I would recommend Dr Belisa Vranich. It takes some practice to unlearn how we have been breathing all this while and how we used to breath in early childhood.

## Our breathwork routine

Here are the specific practices I follow and benefit from.

### The 4-7-8 breath

It all starts the night before. To improve sleep we use the 4-7-8 breathing technique just before sleeping. It is extremely relaxing and helps to fall asleep so much faster. I learnt it from watching Dr Andrew Weil's video recommended from James Nestor's book. We do it once a day right before sleeping, or any time during the day if the stress level gets really high. The technique is really simple, touch the roof of your mouth with your tongue, inhale for 4 seconds, hold for 7 seconds and then exhale for 8 seconds, repeat this 4-7-8 cycle 4 times. Takes less than 90 seconds total. As with everything else, takes several weeks of consistent practice to see the benefits. There is an app for the 4-7-8 breath that it does the time tracking for you so that you only have to focus on breathing.

### The pre-workout practice

I got this protocol from a Brian Mackenzie's video recommended from James Nestor's book. It goes like this:

1. Cycle 1
  - Repeat 5 times
      - 2 second inhale
      - 2 second exhale
  - 20 pulse breaths
  - 20 second exhale hold


2. Cycle 2
  - Repeat 5 times
      - 3 second inhale
      - 3 second exhale
  - 20 pulse breaths
  - 20 second exhale hold
  

3. Cycle 3
  - Repeat 5 times
      - 4 second inhale
      - 4 second exhale
  - 20 pulse breaths
  - 20 second exhale hold
  
This protocol stimulates the sympathetic nervous system so that the body and mind are prepared for a stressful activity i.e. a workout routine. I do this prior to my workout. When I first started doing this, I did this with some healthy skepticism as to how much benefit I would get out of it even though I understood why it should help (release of adrenaline and noradrenaline). Over a period of a few weeks I realized it really made a difference in that my workouts did not seem as strenuous even though I was lifting heavier than before and more specifically I didn't feel totally enervated after a 12 minute EMOM. On some off chance that I forget doing this I immediately feel a difference during my workout and realize that it is because I missed my pre-workout breathwork and then I go back and do it.

### Breathing pattern during the workout

Other than not breathing through the mouth unless absolutely necessary, I follow a simple rule: exhale while exerting effort, inhale when not exerting effort. This seems counter-intuitive, for the longest time I used to breath in the opposite way, so for example, if I was doing a push press I would inhale while pushing up. As I now understand that is the exact opposite of what I should have been doing. So now, before doing a push press, I take a deep "belly" breath, try to feel the air filling up my lungs and pushing outwards 360 degrees in my belly (I know this sounds abstract, but give it a try) and then press with everything tight and the air in the belly still supporting all the weight that I am pressing. I exhale slowly when I bring the barbell down after completing the press. Sometimes, when I really need to find that last bit of energy (around the 3rd rep of the 5th set) I would probably exhale slowly while pressing and a small inhale at the top but generally I try to avoid that. Deadlifts are similar, I take one last deep breath with my hands on the trapbar handles and the body in position, complete the lift, slowly put the trapbar down and then breath again. Occasionaly, I would do an inhale at the top of the lift.

Having the air inside creates stability and gives support to the spine for the lift. It creates a world of difference.

### Inversions

Chances are you may have seen a Yogic asan called "Sheershasan" or an "inverted headstand". There are numerous benefits of doing an inversion (there are several variants of it) such as increased bloodflow to the brain (improved cognition), increased core strength, moving the lymphatic fluids to the upper half of the body (since we are inverted) to get rid of toxins from the body but at the same time it is also an exercise for the diaphragm. Just like exercises for the muscles we can see, such as curls for the biceps, the inversion is an exercise for the diaphragm that we do not see. The diaphragm is the major muscle of respiration and can also be made stronger by doing specific exercises, just like any other muscle.

I use a specific contraption called the feetup trainer that makes doing an inversion easier. 

### The physiological sigh

This is one of the quickest way to engage your para-sympathetic nervous system (the so called "rest and digest"). In a way this is the opposite of the protocol I practice pre-workout. Engaging the para-sympathetic nervous system makes us less aroused and therefore less anxious and more calm. Life throws up situations and many times we react to things in ways we know are counter-productive but still we cannot stop ourselves. This protocol comes in handy in such situations. The protocol is very simple and reminds me of how small children sob, take two pulse inhales through the nose and then one long exhale through the mouth, repeat 3 to 5 times. At a physiological level what this protocol is doing is offloading the maximum amount of carbon dioxide.

I would refer you to Dr Andrew Huberman's podcast for understanding the biology behind this protocol.

### Taping the mouth while sleeping

I tape my mouth while sleeping. It is just a small tape put vertically over the center of the lips. It is to ensure that I do not breath through the nose even while sleeping. I know it sounds at least a little bit weird, but it has definitely improved the quality of my sleep. Even with fewer hours of sleep I feel refreshed when I wake up (I am not suggesting this as a way of getting by with less sleep, certainly not, I wish everyone is able to get a good 8-hour sleep). The first time I tried it, I had to take it off after a couple of hours, but then the next day it was fine and from then on I haven't slept a night without the tape on.

## Chapter 9: At a glance

***

1. There are several breathwork protocols that we can easily incorporate in our daily lives to improve sleep, workout performance and reducing anxiety.

2. The 4-7-8 protocol, the pre-workout protocol for engaging the sympathetic nervous system, the physiological sigh for reducing anxiety are some of the techniques I use.

3. Please lookup the people and books I mentioned in this chapter, they are all very worth of your time.
