# Podcasts, Videos and References

As one of my professors in graduate school used to say, read this for cultural enrichment, I am providing here a list of links from the Internet that I stumbled upon and found useful. Make what you will of it.

## General

**Found My Fitness by Dr Rhonda Patrick**

[https://www.foundmyfitness.com/](https://www.foundmyfitness.com/)

If you like an academic take on the latest research in health & fitness then you will love this.


## Supplements

**Dr Rhonda Patrick's supplement list (not endorsed by her)**

[https://fastlifehacks.com/dr-rhonda-patricks-supplements-list/](https://fastlifehacks.com/dr-rhonda-patricks-supplements-list/)

I found this page by literally doing a Google search one day thinking, I have watched so many of her videos, wonder what supplements does she take?


## Circadian Rhythm & TRE

**Dr Satchin Panda's TED Talk on Circadian Rhythm**

[https://www.youtube.com/watch?v=erBJuxVR7IE](https://www.youtube.com/watch?v=erBJuxVR7IE)

Health lies in healthy circadian habits.

**Dr Satchin Panda with Dr Rhonda Patrick on TRE and Circadian Rhythm**

[https://www.youtube.com/watch?v=-R-eqJDQ2nU](https://www.youtube.com/watch?v=-R-eqJDQ2nU)

90 minutes of extremely detailed discussion on Circadian Rhythm and TRE.

## Fasting Mimicking Diet

**Dr Valter Longo with Dr Rhonda Patrick on fasting mimicking diet and it's effect on longevity and serious diseases**

[https://www.youtube.com/watch?v=d6PyyatqJSE](https://www.youtube.com/watch?v=d6PyyatqJSE)

How fasting helps in ways you may not have thought of.

## Exercise

**Jason Walsh, how do actors get ready in shape for movies**

[https://www.youtube.com/watch?v=y5-R-TICKSw](https://www.youtube.com/watch?v=y5-R-TICKSw)

Inspirational!

**Aamir Khan, Dangal body transformation**

[https://www.youtube.com/watch?v=1aVw1gZ9Ncg](https://www.youtube.com/watch?v=1aVw1gZ9Ncg)

I watch this if I ever feel like skipping a workout!!

## Links to Papers

During the course of writing this book, I looked up academic papers on topics I wanted to know more. While the book chronicles my personal journey, I did not want it to be just about my personal experiences. Life is too short and the ocean of knowledge is too vast, it would be foolish not to take advantage of existing literature.

Here is a chapter wise listing of papers I referred to.

### Chapter 11, Our diet now

- Caffeine stimulation of cortisol secretion across the waking hours in relation to caffeine intake levels

- Cruciferous Vegetables and Human Cancer Risk: Epidemiologic Evidence and Mechanistic Basis
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2737735/

- Broccoli sprouts: An exceptionally rich source of inducers of enzymes that protect against chemical carcinogens https://www.ncbi.nlm.nih.gov/pmc/articles/PMC23369/

- Sulforaphane: Its “Coming of Age” as a Clinically Relevant Nutraceutical in the Prevention and Treatment of Chronic Disease https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6815645/

- The Seed of Industrial Hemp (Cannabis sativa L.): Nutritional Quality and Potential Functionality for Human Health and Nutrition, https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7400098/
