# From here, where?

```{r echo=FALSE}
library(jpeg)
library(grid)
img <- readJPEG("pictures/before_and_after.jpg")
grid.raster(img)
```

Here are the customary before, after and the not  so customer the year after pictures. I am not a particularly picture friendly person but I do think a picture here highlights the amount of change much more so than numbers ever can.

The good thing about journaling (or writing a book for that matter) is that when you go back and revisit the written word it immediately transports you back in time and then hindsight makes you realize "oh, that is what I was thinking, how naive was I?". What I think now about the road ahead is different from what I was thinking same time last year which is what was documented in the first edition of this book. Last year I was thinking purely in terms of fitness goals but now my field of view is much wider. Anyhow, I am keeping the section from the first edition as is and adding a new one for the second edition as well.

## The road ahead, the 2021 version

While 2 years of work cannot bring back 2 lost decades of very little work on my physical and mental health, but the human body is still a very resilient machine. I want to extend my new found levels of physical fitness and mental alacrity to explore things I always wanted to do but never thought I could do: be a more outdoors person and spend more time in nature (hiking, mountaineering), learn new skills (swimming), read more books (8 books and counting in 2021), teach at a university, but most importantly, find a purpose that puts everything in perspective and makes everything worthwhile.

## The road ahead, from the first edition

What do we do when our target is met? The proverbial last mile is extremely hard as we are finding out and you can see in the charts presented in the previous chapters. Going with the optimistic assumption that we will achieve our weight and strength targets in the next 2 to 3 months, what do we do next?

The natural answer is that sustaining ourselves at that level of health is going to be a challenge in itself and and a tough one at that. What I feel at this time is that this has been such a hard fought (not to mention expensive) battle that the very thought that this could all go away sends a chill down the spine. It is also true that I have been up this hill before and slided back.

What is going to help is to set a new target, that will change the problem from just being one of sustainence to one of achieving a new target. Setting your eyes on the next peak gives an aspirational goal to look up to. Aspirations make you wake up in the morning and get moving. When aspirations are standing on the legs of recent achievements, anything is possible.

My younger one wants to get into wrestling, he is 7 years old. Maybe he and I will train together some day! Let's see where this mid life "obsession" takes me.

