# Links to Papers

During the course of writing this book, I looked up academic papers on topics I wanted to know more. While the book chronicles my personal journey, I did not want it to be just about my personal experiences. Life is too short and the ocean of knowledge is too vast, it would be foolish not to take advantage of existing literature.

Here is a chapter wise listing of papers I referred to.

## Chapter 11, Our diet now

- Caffeine stimulation of cortisol secretion across the waking hours in relation to caffeine intake levels

- Cruciferous Vegetables and Human Cancer Risk: Epidemiologic Evidence and Mechanistic Basis
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2737735/

- Broccoli sprouts: An exceptionally rich source of inducers of enzymes that protect against chemical carcinogens https://www.ncbi.nlm.nih.gov/pmc/articles/PMC23369/

- Sulforaphane: Its “Coming of Age” as a Clinically Relevant Nutraceutical in the Prevention and Treatment of Chronic Disease https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6815645/

- The Seed of Industrial Hemp (Cannabis sativa L.): Nutritional Quality and Potential Functionality for Human Health and Nutrition, https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7400098/