--- 
title: "Blueberries in My Salad"
author: "Amit Arora"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
link-citations: yes
description: "This book describes a journey that I undertook with my wife to nurture and nourish what is important and give up the rest. Like a salad, life may not be the most appealing lunch option but if you can keep finding the blueberries every now and again, it is both rewarding and fullfilling."
---

```{r setup=TRUE}
library(gt)
library(xts)
library(zoo)
library(dplyr)
library(tidyr)
library(glue)
library(ggplot2)
library(stringr)
library(ggthemes)
library(lubridate)
library(tidyverse)
library(futile.logger)

source("globals.R")


df_P1 <- read_csv(P1_DATA_URL) %>%
  mutate(Date=ymd(Date))
df_P2 <- read_csv(P2_DATA_URL) %>%
  mutate(Date=ymd(Date))

df_p1_starting_weight <- df_P1 %>% filter(Date == min(Date, na.rm=TRUE)) %>% pull(Weight)
df_p2_starting_weight <- df_P2 %>% filter(Date == min(Date, na.rm=TRUE)) %>% pull(Weight)

df_starting_and_target_weights <- data.frame(name=c(P1_NAME, P2_NAME),
                                             Starting=c(df_p1_starting_weight, df_p2_starting_weight),
                                             Target=c(P1_TARGET_WEIGHT, P2_TARGET_WEIGHT),
                                             Ideal=c(P1_IDEAL_WEIGHT, P2_IDEAL_WEIGHT))

df_starting_and_target_weights <- df_starting_and_target_weights %>% 
  gather(metric, value, -name) %>%
  mutate(metric = paste0(metric, " Weight"),
         value = as.numeric(value))

# in this section of the code we will do all our data reading, cleaning, wrangling...basically
# everything except the timeseries forecasting bit so that the rest of the sections simply display the 
# charts based on the data analysis done here. The forecasting is left to its own section later in the code
# because it is based on user input and so it needs to be done redone whenever the input changes.
# setup logging so that traces are shown on the console and in a log file as well
flog.appender(appender.tee(LOG_FILE), name=LOGGER)
# print the parameters used
flog.info(glue("params used:
                START_DATE={START_DATE},
                DATA_DIR={DATA_DIR},
                P1_NAME={P1_NAME},
                P2_NAME={P2_NAME},
                P1_DATA_FPATH={P1_DATA_FPATH},
                P2_DATA_FPATH={P2_DATA_FPATH},
                CAPTION={CAPTION},
                IMPORTANT_DATES_FNAME={IMPORTANT_DATES_FNAME},
                IMPORTANT_DATES_FPATH={IMPORTANT_DATES_FPATH},
                NUDGE_X={NUDGE_X},
                NUDGE_Y={NUDGE_Y},
                P1_TARGET_WEIGHT={P1_TARGET_WEIGHT},
                P1_WEIGHT_CAP={P1_WEIGHT_CAP},
                P1_WEIGHT_FLOOR={P1_WEIGHT_FLOOR},
                P2_TARGET_WEIGHT={P2_TARGET_WEIGHT},
                P2_WEIGHT_CAP={P2_WEIGHT_CAP},
                P2_WEIGHT_FLOOR={P2_WEIGHT_FLOOR}"), name=LOGGER)

# read the raw data for person 1, print basic summary and metadata
df_P1 <- read_csv(P1_DATA_URL) %>%
  mutate(name=P1_NAME) %>%
  arrange(Date) %>%
  mutate(Date=ymd(Date)) %>%
  filter(Date >= START_DATE)
flog.info(glue("read data for {P1_NAME} from {P1_DATA_FPATH}, shape of dataframe={nrow(df_P1)}x{ncol(df_P1)}"), name=LOGGER)
flog.info(head(df_P1), name=LOGGER)
flog.info(summary(df_P1), name=LOGGER)
# read the raw data for person 2, ultimately we want to have this dashboard work the same way
# even if there was only person 1 so put the following in an if checl
if(!is.na(P2_NAME)) {
  df_P2 <- read_csv(P2_DATA_URL) %>%
    mutate(name=P2_NAME) %>%
    arrange(Date) %>%
    mutate(Date=ymd(Date)) %>%
    filter(Date >= START_DATE)
  flog.info(glue("read data for {P2_NAME} from {P2_DATA_FPATH}, shape of dataframe={nrow(df_P2)}x{ncol(df_P2)}"), name=LOGGER)
  flog.info(head(df_P2), name=LOGGER)  
  flog.info(summary(df_P2), name=LOGGER)  
}
# read the important dates csv file. This is needed because we would like to annotate this journey
# so that we can say oh right there was an increase in weight for these days and it followed a birthday party, for example...
if(!is.na(IMPORTANT_DATES_FNAME)) {
  important_dates <- read_csv(IMPORTANT_DATES_FPATH)
  flog.info(glue("read data for important dates from {IMPORTANT_DATES_FNAME},
                  shape of dataframe={nrow(important_dates)}x{ncol(important_dates)}"), name=LOGGER)
  flog.info(head(important_dates), name=LOGGER)  
  flog.info(summary(important_dates), name=LOGGER)  
}
# combine the dataframes, we want to do a side by side analysis for both people
if(!is.na(df_P2)) {
  df <- bind_rows(df_P1, df_P2)
  (df) %>%
    sample_n(5)
  flog.info(glue("combined data for {P1_NAME} and {P2_NAME}, shape of data is {nrow(df)}x{ncol(df)}"), name=LOGGER)
} else {
  flog.info(glue("only {P1_NAME} specified, only analyzing data for one person"), name=LOGGER)
  df <- df_P1
}
# get the data in tidy format i.e. Each variable must have its own column.
# Each observation must have its own row.
# Each value must have its own cell.
# see https://r4ds.had.co.nz/tidy-data.html
flog.info("converting the data to tidy format", name=LOGGER)
df_tidy <- df %>%
  gather(metric, value, -Date, -name) %>%
  mutate(value=as.numeric(value))
df_tidy %>%
  sample_n(5)
flog.info(glue("shape of the tidy dataframe is {nrow(df_tidy)}x{ncol(df_tidy)}"), name=LOGGER)
# determine the per day weight loss dataframe by
# calculating loss as weight - the one previous value of weight
# this is done by first grouping the dataframe by name since it has
# data for two people and then arranging by date while maintaining
# the grouping (NOTE: .by_group=TRUE)
df_wt_loss <- df_tidy %>%
  filter(metric=="Weight") %>%
  select(name, Date, value) %>%
  group_by(name) %>%
  arrange(Date, .by_group=TRUE) %>%
  mutate(loss_per_day = -1*(value-lag(value, 1)))  %>%
  mutate(loss_per_day_7_day_ma=rollapply(loss_per_day, 7, mean,align='right',fill=NA))
# is the curse of the weekend real? Assign the day to each date so that we can determine
# if say the weight loss eventually after the weekend was very less or maybe not even there...
df_wt_loss <- df_wt_loss %>%
  mutate(day = weekdays(as.Date(Date)))
# determine how much of theweight loss target has been achieved, this is done by finding the starting
# weight (configured), target weight (configured) and seeing how far each person has reached based on
# what their current weight is. This percentage is used to display a gauge (like the needle of a speedometer)
p1_starting_weight <- df_tidy %>% filter(name==P1_NAME & metric=="Weight") %>% head(1) %>% pull(value)
p1_latest_weight <- df_tidy %>% filter(name==P1_NAME & metric=="Weight") %>% tail(1) %>% pull(value)
# weight loss would be negative when calculated so multiply by -1
p1_wt_lost_as_pct <- -1*100*((p1_latest_weight-p1_starting_weight)/p1_starting_weight)
p2_starting_weight <- df_tidy %>% filter(name==P2_NAME & metric=="Weight") %>% head(1) %>% pull(value)
p2_latest_weight <- df_tidy %>% filter(name==P2_NAME & metric=="Weight") %>% tail(1) %>% pull(value)
p2_wt_lost_as_pct <- -1*100*((p2_latest_weight-p2_starting_weight)/p2_starting_weight)
p1_target_achieved_pct <- (p1_starting_weight-p1_latest_weight)/(p1_starting_weight-P1_TARGET_WEIGHT)*100
p2_target_achieved_pct <- (p2_starting_weight-p2_latest_weight)/(p2_starting_weight-P2_TARGET_WEIGHT)*100
flog.info(glue("p1_starting_weight={p1_starting_weight}, p1_latest_weight={p1_latest_weight},
                p2_starting_weight={p2_starting_weight}, p2_latest_weight={p2_latest_weight},
                p1_target_achieved_pct={p1_target_achieved_pct}, p2_target_achieved_pct={p2_target_achieved_pct}"), name=LOGGER)
# daily weight loss, this is important for a lot of charts and tables
# not the use of group by (name) and then lag. The dataframe is already sorted
# in asc order of time, so if the weight is reducing the daily_wt_loss would be a 
# -ve number, for several charts and tables this is multiplied with -1 so provide
# the absolute loss
df_daily_wt_loss <- df_tidy %>%
  filter(metric == "Weight") %>%
  group_by(name) %>%
  mutate(daily_wt_loss = value - lag(value))
# how many days did it take for each pound to drop? This is found by finding the max date i.e. the last date
# on which each weight (as a whole number, so 230, 229 etc) was seen and then subtracting that date from
# the last date of the previous highest weight. So if 230 was say the 20th pound to drop (if we started from 250 say)
# then the number of days between 231 and 230 becomes the number of days it took to lose the 20th pound.
df_days_to_next_drop <- df_daily_wt_loss %>%
  mutate(value = floor(value)) %>%
  ungroup() %>%
  group_by(name, value) %>%
  summarize(Date=max(Date)) %>%
  arrange(desc(Date)) %>%
  mutate(value_diff=value-lag(value), days=abs(as.numeric(Date-lag(Date)))) %>%
  replace_na(list(value_diff = 0, days = 0)) %>%
  mutate(value=value-min(value)) %>%
  filter(value != 0)
# read the precalculated forecasts and target achievement data 
# this is needed because shinyapps.io does not support Prophet (in the sense there are errors in installing it)
df_forecast_p1 <- read_csv(P1_FORECAST_FPATH) %>%
            select(y, yhat, yhat_lower, yhat_upper, ds)
# convert to xts as that is why dygraph likes
df_forecast_p1 <- xts(df_forecast_p1 %>%
                        select(-ds),
                      order.by = df_forecast_p1$ds)
df_target_achieved_p1 <- read_csv(P1_TARGET_ACHIEVED_FPATH)
df_forecast_p2 <- read_csv(P2_FORECAST_FPATH) %>%
            select(y, yhat, yhat_lower, yhat_upper, ds)
df_forecast_p2 <- xts(df_forecast_p2 %>%
                        select(-ds),
                      order.by = df_forecast_p2$ds)
df_target_achieved_p2 <- read_csv(P2_TARGET_ACHIEVED_FPATH)
# read body measurements file
df_measurements <- read_csv(MEASUREMENTS_FPATH)
df_measurements <- df_measurements %>%
  filter(measurement %in% MEASUREMENTS_TO_KEEP)
flog.info("all done with the initial data read and wrangling", name=LOGGER)

```

# Preface

This is neither a book on salads, nor a commentary on life. What it is, is a journal of experiences that my wife and me had in our journey towards being fit and strong.  Like a salad, day to day life may not be the most appealing lunch option, but just like a good salad if you can keep finding the blueberries every now and again, it is both rewarding and fullfilling. The small and big milestones we achieved during our journey kept us going, just like the blueberries in our salad.

I wanted to write a book documenting our (would be more appropriate to say my) fat to fit journey on a day to day or at least a week by week basis. As things progressed, and I looked around, I realized that we were probably the million'th couple in the world doing this and the Internet was filled with blogs and YouTube videos that document in great detail very successful, inspiring and transformational stories. Why was I wanting to reinvent the wheel by writing our story on the same lines? I realized that while a daily or weekly journal was not something i could do but definitely there were "topics" on which i would like to pen down my thoughts. For example, the most often asked question, "What diet are we following?", "Do I really need a trainer?", "Just tell me how long would it take to lose 10 pounds" and so on. Therefore I decided to write this book as a collection of essays on these and other related topics.

It has been more than 6 months since we started this journey and I feel that we have learnt so much that it is important to document this first and foremost for our own selves and then also for anyone who might be interested (i hope someone is). After all, it is one thing to see someone famous transform and another thing to see someone you know or could relate to (middle aged Punjabi NRI couple anyone?) do the same and then realize "If they could do it, so can I".

We took daily measurements for our weight and other biometrics and they were automatically synced via an app on our phone. This is huge, daily tracking enables, even forces, conversations around progress (or lack thereof) towards your targets. It keeps you honest and on track. What it also enables is to see the big picture over time, such as are you slowing down, do you need to make adjustments to your routine, how much that elaborate weekend dinner set you back? For me personally, as a data scientist it was fascinating to collect the raw data, find patterns, gain insights and also get some forecasts done (when would we reach our target weight?).

Over time I understood that while the desire for weight loss was what got me here, but what i was really gaining was good health and strength. To reduce the benefits of what we were doing to just burning calories and losing tens of pounds now seems like a terrible underselling of the idea of fitness. The human body is a fascinating machine capable of wonderful things, good health is a state of both mind and body. Exercise and healthy eating habits help both mind and body. If you do not have any serious health issues there isn't really any excuse for not exercising regularly and eating healthy. As it is said "शरीरमाद्यं खलु धर्मसाधनम्" i.e. the body is the instrument of all good deeds.

Finally, nothing in this book should be interpreted as me recommending anything, a written version of my musings is what this is. An experiment with a sample size of N=2 i.e. statistically irrelevant!


